name: python-carnot-environment
channels:
        - conda-forge
dependencies:
        - python
        - numpy
        - pip
        - pip:
                - matplotlib
                - pandas
                - jupyter_contrib_nbextensions
